apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicea
  labels:
    run: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      run: servicea
  template:
    metadata:
      labels:
        run: servicea
    spec:
      containers:
      - name: servicea
        image: IMAGENAME
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: servicea
  labels:
    run: servicea
spec:
  selector:
    run: servicea
  ports:
  - port: 80
    targetPort: 5000
